name: streamlit-example
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.9
- conda
- matplotlib==3.5.2
- matplotlib-inline==0.1.3
- pandas=1.3.4
- patsy=0.5.2
- pillow=9.0.1
- pip=21.2.4
- plotly=5.6.0
- scipy=1.7.3
- numpy
- pickle5==0.0.12
- pip:
  - streamlit
  - streamlit-option-menu==0.3.2
  - scikit-learn==1.0.2
  - sklearn==0.0
